version: "3.8"
services:
  postgres:
    image: postgres:13.12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=concurrency
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
  redis:
    image: redis:7.2.1
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis/:/data
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    